import time

# print("")
# time.sleep(0.5)
# print(" |")
# time.sleep(0.5)
# print(" |                   _       _   _             ")
# time.sleep(0.5)
# print(" |    _____   _____ | |_   _| |_(_) ___  _ __  ")
# time.sleep(0.5)
# print(" |   / _ \ \ / / _ \| | | | | __| |/ _ \| '_ \ ")
# time.sleep(0.5)
# print(" |   | __/\ V / (_) | | |_| | |_| | (_) | | | |")
# time.sleep(0.5)
# print(" |   \___| \_/ \___/|_|\__,_|\__|_|\___/|_| |_|")
# time.sleep(0.5)
# print(" |")
# time.sleep(0.5)
# print(" |            __    _                  _   ")
# time.sleep(0.5)
# print(" |      ___  / _|  | |_ _ __ _   _ ___| |_ ")
# time.sleep(0.5)
# print(" |     / _ \| |_   | __| '__| | | / __| __|")
# time.sleep(0.5)
# print(" |    | (_) |  _|  | |_| |  | |_| \__ \ |_ ")
# time.sleep(0.5)
# print(" |     \___/|_|     \__|_|   \__,_|___/\__|")
# time.sleep(0.5)
# print(" |")
# time.sleep(0.5)
# print(" |")
# time.sleep(0.5)
# print(" |")

print(" | "); time.sleep(0.3)
print(" | "); time.sleep(0.3)
print(" |                  _       _   _                      __  "); time.sleep(0.3)
print(" |   _____   _____ | |_   _| |_(_) ___  _ __     ___  / _| "); time.sleep(0.3)
print(" |  / _ \ \ / / _ \| | | | | __| |/ _ \| '_ \   / _ \| |_  "); time.sleep(0.3)
print(" |  | __/\ V / (_) | | |_| | |_| | (_) | | | | | (_) |  _| "); time.sleep(0.3)
print(" |  \___| \_/ \___/|_|\__,_|\__|_|\___/|_| |_|  \___/|_|   "); time.sleep(0.3)
print(" |                                                         "); time.sleep(0.3)
print(" |                                       _   _             "); time.sleep(0.3)
print(" |   ___ ___   ___  _ __   ___ _ __ __ _| |_(_) ___  _ __  "); time.sleep(0.3)
print(" |  / __/ _ \ / _ \| '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \ "); time.sleep(0.3)
print(" | | (_| (_) | (_) | |_) |  __/ | | (_| | |_| | (_) | | | |"); time.sleep(0.3)
print(" |  \___\___/ \___/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|"); time.sleep(0.3)
print(" |                 |_|                                     "); time.sleep(0.3)
print(" | "); time.sleep(0.3)
